#!/bin/bash

echo "🔍 Analyzing CSS usage across the site..."
echo "=========================================="

# Get all CSS class definitions
echo "📋 Extracting CSS class definitions..."
CSS_CLASSES=$(grep -h "\." assets/css/*.css | grep -o '\.[a-zA-Z][a-zA-Z0-9_-]*' | sort | uniq)

# Get all classes used in HTML/Markdown
echo "📋 Extracting used classes from templates..."
USED_CLASSES=$(grep -r "class=" --include="*.html" --include="*.md" . | grep -o 'class="[^"]*"' | tr ' ' '\n' | grep -o '[a-zA-Z][a-zA-Z0-9_-]*' | sort | uniq)

# Find potentially unused classes
echo "�� Finding potentially unused CSS classes..."
echo ""

POTENTIALLY_UNUSED=""
for css_class in $CSS_CLASSES; do
    # Remove the leading dot for comparison
    class_name=$(echo "$css_class" | sed 's/^\.//')
    
    # Check if this class is used anywhere
    if ! echo "$USED_CLASSES" | grep -q "^$class_name$"; then
        POTENTIALLY_UNUSED="$POTENTIALLY_UNUSED $css_class"
    fi
done

echo "⚠️  POTENTIALLY UNUSED CSS CLASSES:"
echo "$POTENTIALLY_UNUSED" | tr ' ' '\n' | grep -v '^$' | head -20

echo ""
echo "📊 SUMMARY:"
echo "- Total CSS classes defined: $(echo "$CSS_CLASSES" | wc -l)"
echo "- Total classes used in templates: $(echo "$USED_CLASSES" | wc -l)"
echo "- Potentially unused classes: $(echo "$POTENTIALLY_UNUSED" | wc -w)"

echo ""
echo "⚠️  WARNING: This analysis may have false positives!"
echo "   Some classes might be used dynamically via JavaScript"
echo "   or generated by Jekyll plugins. Always test before removing."
